
# this is a YAML anchor: https://yaml.org/spec/1.2.2/#alias-nodes
# it's kind of a trivial example because this field also has a documentation block defined: https://docs.getdbt.com/docs/build/documentation#using-docs-blocks
descriptions: &feed_id_desc '{{ doc("feed_id_desc") }}'

version: 2

models:
  - name: stg_routes
    description: Staging layer for routes data from GTFS feed
    columns:
      - name: _feed_id
        description: *feed_id_desc
      - name: route_id
        description: '{{ doc("routes_route_id") }}'
      - name: agency_id
        description: '{{ doc("routes_agency_id") }}'
      - name: route_short_name
        description: '{{ doc("routes_route_short_name") }}'
      - name: route_long_name
        description: '{{ doc("routes_route_long_name") }}'
      - name: route_desc
        description: '{{ doc("routes_route_desc") }}'
      - name: route_type
        description: '{{ doc("routes_route_type") }}'
      - name: route_url
        description: '{{ doc("routes_route_url") }}'
      - name: route_color
        description: '{{ doc("routes_route_color") }}'
      - name: route_text_color
        description: '{{ doc("routes_route_text_color") }}'
      - name: route_sort_order
        description: '{{ doc("routes_route_sort_order") }}'
      - name: continuous_pickup
        description: '{{ doc("routes_continuous_pickup") }}'
      - name: continuous_drop_off
        description: '{{ doc("routes_continuous_drop_off") }}'
      - name: network_id
        description: '{{ doc("routes_network_id") }}'

  - name: stg_trips
    description: Staging layer for trips data from GTFS feed
    columns:
      - name: _feed_id
        description: *feed_id_desc
      - name: route_id
        description: '{{ doc("trips_route_id") }}'
      - name: service_id
        description: '{{ doc("trips_service_id") }}'
      - name: trip_id
        description: '{{ doc("trips_trip_id") }}'
      - name: trip_headsign
        description: '{{ doc("trips_trip_headsign") }}'
      - name: trip_short_name
        description: '{{ doc("trips_trip_short_name") }}'
      - name: direction_id
        description: '{{ doc("trips_direction_id") }}'
      - name: block_id
        description: '{{ doc("trips_block_id") }}'
      - name: shape_id
        description: '{{ doc("trips_shape_id") }}'
      - name: wheelchair_accessible
        description: '{{ doc("trips_wheelchair_accessible") }}'
      - name: bikes_allowed
        description: '{{ doc("trips_bikes_allowed") }}'

  - name: stg_calendar
    description: Staging layer for calendar data from GTFS feed
    columns:
      - name: _feed_id
        description: *feed_id_desc
      - name: service_id
        description: '{{ doc("calendar_service_id") }}'
      - name: monday
        description: '{{ doc("calendar_monday") }}'
      - name: tuesday
        description: '{{ doc("calendar_tuesday") }}'
      - name: wednesday
        description: '{{ doc("calendar_wednesday") }}'
      - name: thursday
        description: '{{ doc("calendar_thursday") }}'
      - name: friday
        description: '{{ doc("calendar_friday") }}'
      - name: saturday
        description: '{{ doc("calendar_saturday") }}'
      - name: sunday
        description: '{{ doc("calendar_sunday") }}'
      - name: start_date
        description: '{{ doc("calendar_start_date") }}'
      - name: end_date
        description: '{{ doc("calendar_end_date") }}'

  - name: stg_calendar_dates
    description: Staging layer for calendar dates data from GTFS feed
    columns:
      - name: _feed_id
        description: *feed_id_desc
      - name: service_id
        description: '{{ doc("calendar_dates_service_id") }}'
      - name: date
        description: '{{ doc("calendar_dates_date") }}'
      - name: exception_type
        description: '{{ doc("calendar_dates_exception_type") }}'

  - name: stg_stops
    description: Staging layer for stops data from GTFS feed
    columns:
      - name: _feed_id
        description: *feed_id_desc
      - name: stop_id
        description: '{{ doc("stops_stop_id") }}'
      - name: stop_code
        description: '{{ doc("stops_stop_code") }}'
      - name: stop_name
        description: '{{ doc("stops_stop_name") }}'
      - name: tts_stop_name
        description: '{{ doc("stops_tts_stop_name") }}'
      - name: stop_desc
        description: '{{ doc("stops_stop_desc") }}'
      - name: stop_lat
        description: '{{ doc("stops_stop_lat") }}'
      - name: stop_lon
        description: '{{ doc("stops_stop_lon") }}'
      - name: zone_id
        description: '{{ doc("stops_zone_id") }}'
      - name: stop_url
        description: '{{ doc("stops_stop_url") }}'
      - name: location_type
        description: '{{ doc("stops_location_type") }}'
      - name: parent_station
        description: '{{ doc("stops_parent_station") }}'
      - name: wheelchair_boarding
        description: '{{ doc("stops_wheelchair_boarding") }}'
      - name: stop_timezone
        description: '{{ doc("stops_stop_timezone") }}'
      - name: level_id
        description: '{{ doc("stops_level_id") }}'
      - name: platform_code
        description: '{{ doc("stops_platform_code") }}'

  - name: stg_stop_times
    description: Staging layer for stop times data from GTFS feed
    columns:
      - name: _feed_id
        description: *feed_id_desc
      - name: trip_id
        description: '{{ doc("stop_times_trip_id") }}'
      - name: arrival_time
        description: '{{ doc("stop_times_arrival_time") }}'
      - name: departure_time
        description: '{{ doc("stop_times_departure_time") }}'
      - name: arrival_seconds
        description: Arrival time converted to seconds since midnight
      - name: departure_seconds
        description: Departure time converted to seconds since midnight
      - name: stop_id
        description: '{{ doc("stop_times_stop_id") }}'
      - name: stop_sequence
        description: '{{ doc("stop_times_stop_sequence") }}'
      - name: stop_headsign
        description: '{{ doc("stop_times_stop_headsign") }}'
      - name: pickup_type
        description: '{{ doc("stop_times_pickup_type") }}'
      - name: drop_off_type
        description: '{{ doc("stop_times_drop_off_type") }}'
      - name: shape_dist_traveled
        description: '{{ doc("stop_times_shape_dist_traveled") }}'
      - name: timepoint
        description: '{{ doc("stop_times_timepoint") }}'
      - name: start_pickup_drop_off_window
        description: '{{ doc("stop_times_start_pickup_drop_off_window") }}'
      - name: end_pickup_drop_off_window
        description: '{{ doc("stop_times_end_pickup_drop_off_window") }}'
      - name: continuous_pickup
        description: '{{ doc("stop_times_continuous_pickup") }}'
      - name: continuous_drop_off
        description: '{{ doc("stop_times_continuous_drop_off") }}'
      - name: pickup_booking_rule_id
        description: '{{ doc("stop_times_pickup_booking_rule_id") }}'
      - name: drop_off_booking_rule_id
        description: '{{ doc("stop_times_drop_off_booking_rule_id") }}'
