version: 2

# this is a YAML anchor: https://yaml.org/spec/1.2.2/#alias-nodes
# it's kind of a trivial example because this field also has a documentation block defined: https://docs.getdbt.com/docs/build/documentation#using-docs-blocks
descriptions: &feed_id_desc '{{ doc("feed_id_desc") }}'

sources:
  - name: raw
    description: Raw GTFS data loaded from transit agency feed. Field documentation copied from https://gtfs.org/documentation/schedule/reference/
    tables:
      - name: agency
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - agency_id
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: agency_id
            description: >
              Identifies a transit brand which is often synonymous with a transit agency. Note that in some cases, such as when a single agency operates multiple separate services, agencies and brands are distinct. This document uses the term "agency" in place of "brand". A dataset may contain data from multiple agencies. Required when the dataset contains data for multiple transit agencies.
          - name: agency_name
            description: Full name of the transit agency.
          - name: agency_url
            description: URL of the transit agency.
          - name: agency_timezone
            description: Timezone where the transit agency is located. If multiple agencies are specified in the dataset, each must have the same agency_timezone.
          - name: agency_lang
            description: Primary language used by this transit agency. Should be provided to help GTFS consumers choose capitalization rules and other language-specific settings for the dataset.
          - name: agency_phone
            description: A voice telephone number for the specified agency. This field is a string value that presents the telephone number as typical for the agency's service area. It may contain punctuation marks to group the digits of the number. Dialable text (for example, TriMet's "503-238-RIDE") is permitted, but the field must not contain any other descriptive text.
          - name: agency_fare_url
            description: URL of a web page that allows a rider to purchase tickets or other fare instruments for that agency online.
          - name: agency_email
            description: Email address actively monitored by the agency's customer service department. This email address should be a direct contact point where transit riders can reach a customer service representative at the agency.

      - name: stops
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - stop_id
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: stop_id
            description: '{{ doc("stops_stop_id") }}'
          - name: stop_code
            description: '{{ doc("stops_stop_code") }}'
          - name: stop_name
            description: '{{ doc("stops_stop_name") }}'
          - name: tts_stop_name
            description: '{{ doc("stops_tts_stop_name") }}'
          - name: stop_desc
            description: '{{ doc("stops_stop_desc") }}'
          - name: stop_lat
            description: '{{ doc("stops_stop_lat") }}'
          - name: stop_lon
            description: '{{ doc("stops_stop_lon") }}'
          - name: zone_id
            description: '{{ doc("stops_zone_id") }}'
          - name: stop_url
            description: '{{ doc("stops_stop_url") }}'
          - name: location_type
            description: '{{ doc("stops_location_type") }}'
          - name: parent_station
            description: '{{ doc("stops_parent_station") }}'
          - name: wheelchair_boarding
            description: '{{ doc("stops_wheelchair_boarding") }}'
          - name: stop_timezone
            description: '{{ doc("stops_stop_timezone") }}'
          - name: level_id
            description: '{{ doc("stops_level_id") }}'
          - name: platform_code
            description: '{{ doc("stops_platform_code") }}'

      - name: routes
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - route_id
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: route_id
            description: '{{ doc("routes_route_id") }}'
          - name: agency_id
            description: '{{ doc("routes_agency_id") }}'
          - name: route_short_name
            description: '{{ doc("routes_route_short_name") }}'
          - name: route_long_name
            description: '{{ doc("routes_route_long_name") }}'
          - name: route_desc
            description: '{{ doc("routes_route_desc") }}'
          - name: route_type
            description: '{{ doc("routes_route_type") }}'
          - name: route_url
            description: '{{ doc("routes_route_url") }}'
          - name: route_color
            description: '{{ doc("routes_route_color") }}'
          - name: route_text_color
            description: '{{ doc("routes_route_text_color") }}'
          - name: route_sort_order
            description: '{{ doc("routes_route_sort_order") }}'
          - name: continuous_pickup
            description: '{{ doc("routes_continuous_pickup") }}'
          - name: continuous_drop_off
            description: '{{ doc("routes_continuous_drop_off") }}'
          - name: network_id
            description: '{{ doc("routes_network_id") }}'

      - name: trips
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - trip_id
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: route_id
            description: '{{ doc("trips_route_id") }}'
          - name: service_id
            description: '{{ doc("trips_service_id") }}'
          - name: trip_id
            description: '{{ doc("trips_trip_id") }}'
          - name: trip_headsign
            description: '{{ doc("trips_trip_headsign") }}'
          - name: trip_short_name
            description: '{{ doc("trips_trip_short_name") }}'
          - name: direction_id
            description: '{{ doc("trips_direction_id") }}'
          - name: block_id
            description: '{{ doc("trips_block_id") }}'
          - name: shape_id
            description: '{{ doc("trips_shape_id") }}'
          - name: wheelchair_accessible
            description: '{{ doc("trips_wheelchair_accessible") }}'
          - name: bikes_allowed
            description: '{{ doc("trips_bikes_allowed") }}'

      - name: stop_times
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - trip_id
              - stop_sequence
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: trip_id
            description: '{{ doc("stop_times_trip_id") }}'
          - name: arrival_time
            description: '{{ doc("stop_times_arrival_time") }}'
          - name: departure_time
            description: '{{ doc("stop_times_departure_time") }}'
          - name: stop_id
            description: '{{ doc("stop_times_stop_id") }}'
          - name: stop_sequence
            description: '{{ doc("stop_times_stop_sequence") }}'
          - name: stop_headsign
            description: '{{ doc("stop_times_stop_headsign") }}'
          - name: pickup_type
            description: '{{ doc("stop_times_pickup_type") }}'
          - name: drop_off_type
            description: '{{ doc("stop_times_drop_off_type") }}'
          - name: shape_dist_traveled
            description: '{{ doc("stop_times_shape_dist_traveled") }}'
          - name: timepoint
            description: '{{ doc("stop_times_timepoint") }}'
          - name: start_pickup_drop_off_window
            description: '{{ doc("stop_times_start_pickup_drop_off_window") }}'
          - name: end_pickup_drop_off_window
            description: '{{ doc("stop_times_end_pickup_drop_off_window") }}'
          - name: continuous_pickup
            description: '{{ doc("stop_times_continuous_pickup") }}'
          - name: continuous_drop_off
            description: '{{ doc("stop_times_continuous_drop_off") }}'
          - name: pickup_booking_rule_id
            description: '{{ doc("stop_times_pickup_booking_rule_id") }}'
          - name: drop_off_booking_rule_id
            description: '{{ doc("stop_times_drop_off_booking_rule_id") }}'

      - name: calendar
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - service_id
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: service_id
            description: '{{ doc("calendar_service_id") }}'
          - name: monday
            description: '{{ doc("calendar_monday") }}'
            data_tests:
            - &calendar_day_bool_test
              accepted_values:
                values: ['0', '1']
          - name: tuesday
            description: '{{ doc("calendar_tuesday") }}'
            data_tests:
              - *calendar_day_bool_test
          - name: wednesday
            description: '{{ doc("calendar_wednesday") }}'
            data_tests:
              - *calendar_day_bool_test
          - name: thursday
            description: '{{ doc("calendar_thursday") }}'
            data_tests:
              - *calendar_day_bool_test
          - name: friday
            description: '{{ doc("calendar_friday") }}'
            data_tests:
              - *calendar_day_bool_test
          - name: saturday
            description: '{{ doc("calendar_saturday") }}'
            data_tests:
              - *calendar_day_bool_test
          - name: sunday
            description: '{{ doc("calendar_sunday") }}'
            data_tests:
              - *calendar_day_bool_test
          - name: start_date
            description: '{{ doc("calendar_start_date") }}'
          - name: end_date
            description: '{{ doc("calendar_end_date") }}'

      - name: calendar_dates
        data_tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - feed_id
              - service_id
              - date
        columns:
          - name: feed_id
            description: *feed_id_desc
          - name: service_id
            description: '{{ doc("calendar_dates_service_id") }}'
          - name: date
            description: '{{ doc("calendar_dates_date") }}'
          - name: exception_type
            description: '{{ doc("calendar_dates_exception_type") }}'
            data_tests:
            - accepted_values:
                values: ['1', '2']
